### ISSUE TITLE
[BUG] "long-method" can't handle many lines of code

### ISSUE THREAD

**Issue by mit-73** [dart-code-checker/dart-code-metrics#1030]
* **Dart code metrics version: 4.19.1**
* **Dart sdk version: ">=2.18.0 <3.0.0"**

<details>
<summary>Configuration</summary>

```yaml
analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maintainability-index: 50
    maximum-nesting: 5
    number-of-parameters: 5
    source-lines-of-code: 50
    technical-debt:
      threshold: 1
      todo-cost: 4
      ignore-cost: 8
      ignore-for-file-cost: 16
      as-dynamic-cost: 16
      deprecated-annotations-cost: 2
      file-nullsafety-migration-cost: 2
      unit-type: "hours"
  rules:
    - avoid-global-state
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-non-null-assertion
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-global-state
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-correct-type-name
    - prefer-first
    - prefer-last
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
```

</details>

**What did you do? Please include the source code example causing the issue.**
There is a problem with "long-method" on `Widget build(BuildContext context)`, it blinks (shows or doesn't show the lint). I think it is because the project was over the limit of the analyzer by the amount of code. This problem has been observed in 4 people with different system environments. Since the problem appeared with MR, I can't connect it to anything else but the limit on the number of lines of code. 

The code is under NDA, there is no way to pass it for testing. Here is the information on the amount of code:

language | files | code | comment | blank | total
-- | -- | -- | -- | -- | --
Dart | 605 | 70,692 | 3,166 | 10,409 | 84,267

<img width="614" alt="2022-10-11 в 17 27 05" src="https://user-images.githubusercontent.com/43699145/195105048-4632e193-f999-45ef-9c21-2d2fb9ab0f0c.png">

https://user-images.githubusercontent.com/43699145/195105138-47f0f16b-94c3-4fba-b697-9f6b42467575.mov

**What did you expect to happen?**
I don't expect to see a warning from lint, even more I don't expect a constantly blinking warning from lint.

**What actually happened?**
"long-method" blinks on all `Widget build(BuildContext context)`, so there is also a load on the system because of this.

**Are you willing to submit a pull request to fix this bug?**
Yes, if I can find the time.
