### ISSUE TITLE
[Question] override rules from preset

### ISSUE THREAD

**Issue by hanskenis** [dart-code-checker/dart-code-metrics#1055]
I would like to use the presets, but still be able to override some rules. Like this:

```
dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
  rules:
    - avoid-ignoring-return-values:
      exclude:
        - test/**
  ```

At the moment this doesn't seem to work and i'm still getting warnings on the test files. Am i missing something? Will this be supported in a future release? Thx!

**Comment by incendial** [comment]
@hanskenis hi, is you posted the yaml example as is, then there is a mistake. `exclude` should move more indentation, like:
```
dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
  rules:
    - avoid-ignoring-return-values:
         exclude: <---
          - test/**
```
and that should work
