### ISSUE TITLE
[BUG] `use-setstate-synchronously` doesn't recognize `assert` statements

### ISSUE THREAD

**Issue by DetachHead** [dart-code-checker/dart-code-metrics#1178]
### Environment and configuration

DCM version: 5.5.1
Dart SDK version:  3.0.0-52.0.dev

<details>
<summary>Configuration</summary>

```yaml
dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
```
</details>

### What did you do?

```dart
await doThing();
assert(mounted);
setState(() => {}); // error: use-setstate-synchronously
```

### What did you expect to happen?

no error

### What actually happened?

`use-setstate-synchronously` error

### Participation

- [ ] I am willing to submit a pull request for this issue.
