### ISSUE TITLE
[BUG] Multiple analyzer plugins can't be enabled

### ISSUE THREAD

**Issue by cbenhagen** [dart-code-checker/dart-code-metrics#1213]
### Environment and configuration

Starting from Flutter 3.7.6 it is not possible to use multiple ananlyzer plugins anymore. So the following config will throw the following:
`warning: Multiple plugins can't be enabled`

### What did you do?

```yaml
include: package:lint/analysis_options.yaml

analyzer:
  errors:
    ...
  exclude:
    ...
  plugins:
    - dart_code_metrics
    - custom_lint

...
```

### What did you expect to happen?

I expect to be able to use dart_code_metrics together with other analyzer plugins.

### What actually happened?

`warning: Multiple plugins can't be enabled`

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Please consider integrating with [custom_lint](https://pub.dev/packages/custom_lint).
