### ISSUE TITLE
[BUG] `format-comment` false positive

### ISSUE THREAD

**Issue by FMorschel** [dart-code-checker/dart-code-metrics#1232]
### Environment and configuration

DCM version: 5.7.3
Dart SDK version: 3.0.0

<details>
<summary>Configuration</summary>

```yaml
dart_code_metrics:
  rules:
    - double-literal-format
    - format-comment
    - member-ordering-extended:
        alphabetize: false
        order:
          - constructors
          - named-constructors
          - factory-constructors
          - static-getters-setters
          - static-const-public-fields
          - static-const-private-fields
          - static-final-public-fields
          - static-final-private-fields
          - static-late-final-public-fields
          - static-late-final-private-fields
          - static-late-public-fields
          - static-late-private-fields
          - static-public-fields
          - static-private-fields
          - const-public-fields
          - const-private-fields
          - final-public-fields
          - final-private-fields
          - late-final-public-fields
          - late-final-private-fields
          - late-public-fields
          - late-private-fields
          - public-fields
          - private-fields
          - overridden-public-fields
          - overriden-public-methods
          - static-public-methods
          - static-private-methods
          - public-methods
          - private-methods
          - getters-setters
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-immediate-return
    - prefer-last

    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets:
        ignored-names:
          - testFunction
        ignored-annotations:
          - allowedAnnotation
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
```
</details>

### What did you do?

```dart
  // TODO: home.
  // TODO: login.
```

### What did you expect to happen?

No line should trigger since I'm actually formatting them like sentences.

### What actually happened?

When I have two lines of comment one after another, this lint triggers. When there is only one, the lint doesn't trigger.

### Participation

- [ ] I am willing to submit a pull request for this issue.
