### ISSUE TITLE
[BUG] Using code metrics in analysis_options.yaml results in external libraries being analyzed

### ISSUE THREAD

**Issue by GroovinChip** [dart-code-checker/dart-code-metrics#220]
* **Dart code metrics version:**
2.4.1
* **Dart sdk version:**
2.7.0 in project, 2.12.0 globally

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
linter:
  rules:
    - prefer_single_quotes
    - unnecessary_new
    - prefer_contains
    - package_names
    - non_constant_identifier_names
    - library_prefixes
    - library_names
    - implementation_imports
    - file_names
    - camel_case_extensions
    - camel_case_types
    - avoid_empty_else
    - avoid_classes_with_only_static_members

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-arguments: 4
    maximum-nesting: 5
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - no-equal-then-else
```
</details>

**What did you do? Please include the source code example causing the issue.**

I configured my `analysis_options.yaml` file as listed in the configuration section of this issue

**What did you expect to happen?**
I expected the analyzer only to scan my project files, not files from packages I depend on

**What actually happened?**
Files from packages I depend on are being scanned
<img width="1707" alt="Screen Shot 2021-03-13 at 12 20 51 PM" src="https://user-images.githubusercontent.com/4250470/111038392-9df1e000-83f6-11eb-92e8-868fcea17b3b.png">

**Are you willing to submit a pull request to fix this bug?**
I have no experience with working on the analyzer, so probably not.

**Comment by incendial** [comment]
@GroovinChip hi! Could you please share the pubspec.yaml too? Have you tried to run CLI and check will it also analyze external packages? If you could share a minimal example where we can reproduce the problem - that would be very helpful.

**Comment by GroovinChip** [comment]
Hi @incendial thanks for responding! Here's my pubspec.yaml:
```yaml
name: call_manager
description: Call Manager in Flutter
version: 2.4.0+35
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  datetime_picker_formfield: any
  call_number:
    path: ../../packages_and_plugins/call_number
  url_launcher: ^5.2.5
  flutter_local_notifications: ^4.0.1+2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0+1
  package_info: ^0.4.3+4
  permission_handler: ^5.0.1+1
  groovin_widgets: ^1.6.1
  contacts_service: ^0.4.6
  flutter_typeahead: ^2.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.4
  provider: ^5.0.0
  google_fonts: ^1.1.2
  material_design_icons_flutter: ^4.0.5955

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
  dart_code_metrics: ^2.4.1

flutter_icons:
  android: true
  image_path: "assets/icon/call_manager_app_icon.png"
  adaptive_icon_background: "#1976D2"

flutter:

  uses-material-design: true

  assets:
    - android/app/src/main/res/drawable-hdpi/ic_notification.png
    - assets/icon/call_manager_app_icon.png
    - assets/glogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500
```
I have run the CLI and can confirm that it does not analyze external packages. I'll try to get a minimal reproducible example to you shortly.

**Comment by GroovinChip** [comment]
Here's the [example](https://github.com/GroovinChip/code_metrics_bug), although the bug is not appearing there even though the analysis_options.yaml is identical, and a few packages that are being analyzed in my actual app are imported too. The repo for the full app that does have the bug is https://github.com/GroovinChip/CallManager.

**Comment by incendial** [comment]
@GroovinChip thanks for the example, sad that the problem is not appearing there. I will take a closer look.

Do you have a single pubspec and a single analysis_options files?

**Comment by GroovinChip** [comment]
Yes, a single pubspec and a single analysis_options.yaml in both repos

**Comment by incendial** [comment]
I was able to reproduce the bug on the https://github.com/GroovinChip/CallManager, thank you

**Comment by GroovinChip** [comment]
Great! Do you have any thoughts on what the problem might be?

**Comment by incendial** [comment]
Sorry, at first I though that I got it, but I was wrong. Although I am using VSCode and maybe should switch to WebStorm for better changes.

**Comment by GroovinChip** [comment]
Ah ok. Yeah, I'm using Android Studio. I haven't tried to see if VS Code has the same problem. I'm AFK for a while but I can check when I'm back at the computer.

**Comment by incendial** [comment]
Sure, switching to Android Studio didn't work for me, no external packages analysis. 

Could you please open "View analyzer diagnostics" and check the Plugins tab? You should have only a single plugin instance and version.
<img width="455" alt="Screenshot 2021-03-13 at 22 58 55" src="https://user-images.githubusercontent.com/21116742/111042813-42544080-8450-11eb-984f-6cbc4e77de31.png">

**Comment by GroovinChip** [comment]
Sure, here's the output from the Plugins tab:
```
Plugins in use.

Analysis plugins
dart_code_metrics-2.4.1
bootstrap package path: /Users/groov/development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_code_metrics-2.4.1/tools/analyzer_plugin

execution path: /Users/groov/.dartServer/.plugin_manager/cf5be46d4e2f707896f22185da861974/analyzer_plugin/bin/plugin.dart

packages file path: /Users/groov/.dartServer/.plugin_manager/cf5be46d4e2f707896f22185da861974/analyzer_plugin/.packages

name: Dart Code Metrics

version: 1.0.0-alpha.0

Associated contexts:

/Users/groov/development/flutter_projects/apps/call_manager
Performance:

analysis.setContextRoots [9201]

analysis.setPriorityFiles [9847, 42, 46, 291, 60, 38, 39, 72, 283, 97, 39, 38, 101, 157, 39, 90, 165, 39, 102, 144, 39, 158, 38, 147, 38, 157, 38]

analysis.setSubscriptions [9810, 43, 42, 290, 59, 38, 38, 72, 283, 97, 38, 38, 101, 157, 39, 90, 164, 39, 102, 144, 39, 158, 38, 146, 38, 157, 38]

analysis.updateContent [14, 0, 0, 1, 7, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 3, 1, 2, 16, 1, 12, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 194, 194, 194, 194, 10, 63, 29, 116, 26, 20, 2, 14, 42, 48, 30, 38, 14, 0, 3, 2, 29, 26, 25, 4, 4, 15, 3, 21, 31, 26, 2, 26, 16, 24, 24, 23, 24, 22, 24, 46, 19, 15, 15, 3, 2, 1, 20, 1, 15, 23, 31, 22, 1, 2, 28, 32, 4, 21, 1, 1]

completion.getSuggestions [58, 69, 75, 81, 87, 92, 98, 104, 110, 117, 121, 128, 134, 140, 145, 151, 157, 164, 170, 176, 16, 1, 43, 49, 5, 1, 102, 3, 12, 8, 4, 2, 36, 21, 9, 9, 13, 12, 9, 14, 12, 8, 8, 7, 9, 47, 8, 10, 12, 4, 8, 3, 8, 24, 27, 3, 7, 30, 8, 10, 9, 9, 16, 8, 8, 8, 12]

edit.getAssists [83, 411, 12, 23, 25, 31, 19, 59, 2, 19, 14, 3, 1, 1, 38, 3, 2, 21, 2, 2, 34, 6, 4, 3, 6, 22, 23, 3, 2, 2, 4, 9, 11, 1, 3, 1, 1, 2, 2, 13, 31, 12, 15, 3, 2, 2, 1, 26, 3, 2, 1, 1, 2, 1, 3, 3, 2]

edit.getFixes [15, 86, 117, 117, 117, 20, 63, 42, 4, 4, 5, 4, 18, 28, 4, 3, 3, 5, 10, 57, 1]

plugin.versionCheck [54]
```

**Comment by GroovinChip** [comment]
Can confirm the issue occurs in VSCode too
<img width="1173" alt="Screen Shot 2021-03-13 at 3 57 43 PM" src="https://user-images.githubusercontent.com/4250470/111044170-d99ba280-8414-11eb-9a3f-b2f004734e0b.png">

**Comment by incendial** [comment]
Of course! We don't ignore this installed plugins and they appear only after build (thats why I was not able to reproduce it). We should probably add ignores for them. Could you try to add exclude for the ios folder? That should work:
```yaml
analyzer:
  exclude:
    - ios/**
  plugins:
    - dart_code_metrics
```
