### ISSUE TITLE
[BUG] LSP plugin on vim gets crazy when dart-code-metrics is used

### ISSUE THREAD

**Issue by erickzanardo** [dart-code-checker/dart-code-metrics#262]
Hello,

We have been using `dart-code-metrics` on [Flame](https://github.com/flame-engine/flame) from some time and I have noticed that when the plugin is configured on the `analysis_options.yml`, the analyzer starts to get "crazy" and point really strange errors, like this one:

![dart-code-metrics](https://user-images.githubusercontent.com/835641/114237991-42b1ff80-995a-11eb-84af-99555718a5c3.png)

Notice the weird error on "Undefined class" seems like a "confused" code was sent to the analyzer.

I am not sure if this is a problem on dart-code-metrics, or in the vim plugin, but I thought on trying here first as everything works fine if I remove the dart-code-metrics from the plugin section.

Thanks for the time to read this issue and I am willing to help with whatever needed to solve this.

* **Dart code metrics version:** Tested both on `3.0.0-nullsafety.1` and `3.0.0-nullsafety.2`
* **Dart sdk version:** 2.12.2

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  ordered_set: ^3.0.0
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  dart_code_metrics: ^3.0.0-nullsafety.2
  dartdoc: ^0.42.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

flutter:
  uses-material-design: false
```

```yml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_runtimeType_toString
    - omit_local_variable_types
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_relative_imports
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_rethrow_when_possible
    - unrelated_type_equality_checks
    - unsafe_html
    - void_checks

dart_code_metrics:
  rules:
    - prefer-trailing-comma
    - prefer-trailing-comma-for-collection
    - no-equal-then-else
    - no-object-declaration
    - potential-null-dereference
  metrics-exclude:
    - test/**
  metrics:
    number-of-parameters: 8
    number-of-methods: 32
    lines-of-executable-code: 200
    cyclomatic-complexity: 36
```
Both files can also be seen here on github: https://github.com/flame-engine/flame/tree/main/packages/flame

Not sure if this could help, but my nvim config is available here: https://github.com/erickzanardo/dotfiles/blob/master/init.vim
</details>

**Are you willing to submit a pull request to fix this bug?** Would need some guidance, but yes!
