### ISSUE TITLE
Is there a way to exclude plugins from the checks?

### ISSUE THREAD

**Issue by SebastianKlaiber** [dart-code-checker/dart-code-metrics#265]
If I add dart_code_metrics with the following rules, then I also see the violations in the used packages. Is there a way to avoid this behavior? 

```
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
```

<img width="1571" alt="Screenshot 2021-04-14 at 07 29 08" src="https://user-images.githubusercontent.com/59142/114659076-34196e80-9cf3-11eb-860e-be607e454d83.png">

**Comment by dkrutskikh** [comment]
@SebastianKlaiber you can exclude folder with plugins in analysis_options.yaml

```
analyzer:
  exclude:
    - folder_with_plugins/**
  plugins:
    - dart_code_metrics
```

**Comment by nikitadol** [comment]
It works
```
  exclude:
    - 'ios/**'
  plugins:
    - dart_code_metrics
```

**Comment by SebastianKlaiber** [comment]
Thank you

**Comment by PiN73** [comment]
Does it makes sense & is possible to make default behavior match this options?
```yaml
analyzer:
  exclude:
    - ios/.symlinks/**
```

**Comment by PiN73** [comment]
Reproduction steps (macOS needed, tested in Android Studio):
- Create new Flutter app project
- [Setup dart_code_metrics](https://pub.dev/packages/dart_code_metrics#usage)
- Add [cloud_firestore](https://pub.dev/packages/cloud_firestore) dependency
- Run app (to generate Podfile), error will occur (it's firestore+ios issue)
- Open ios/Podfile, uncomment 2nd line `platform :ios, '9.0'` and replace `9` with `10`
- Run app again (to get all dependencies; will take a long for the first time)
- Restart Dart Analysis Server
- Get a lot of problems in Dart Analysis tab :)
<img width="617" alt="image" src="https://user-images.githubusercontent.com/18294052/116017284-d9afd480-a647-11eb-9a80-1e471c13cea7.png">

**Comment by PiN73** [comment]
This analysis_options.yaml
```yaml
analyzer:
  exclude:
    - ios/.symlinks/**
  plugins:
    - dart_code_metrics

dart_code_metrics:
  ...
```
& restarting IDE actually solves the problem
