### ISSUE TITLE
[BUG] avoid-returning-widgets not work

### ISSUE THREAD

**Issue by unger1984** [dart-code-checker/dart-code-metrics#290]
* **Dart code metrics version: 3.1.0**
* **Dart sdk version: 2.13.0-211.6.beta**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
#    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-returning-widgets
```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart
  _buildOther() {
    return Column(
      children: [
        //....
      ],
    );
  }
```

If method have not return type, avoid-returning-widgets not catch it. Work only for:
```dart
  Widget _buildOther() {
    return Column(
      children: [
        //....
      ],
    );
  }
```

PS: Please unban me in the telegram channel, I did not immediately understand that you have a bot and was late in answering the question =)
