### ISSUE TITLE
[BUG] alphabetize member-ordering-extended shows wrong lints

### ISSUE THREAD

**Issue by grafovdenis** [dart-code-checker/dart-code-metrics#345]
* **Dart code metrics version:** 3.2.2
* **Dart sdk version:** 2.12.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
dart_code_metrics:
  rules:
    - member-ordering-extended:
        alphabetize: true
        order:
          - constructors
          - named-constructors
          - overridden-methods
          - public-methods
```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart
class OrderingExample {
  const OrderingExample();

  @override
  String toString() {
    return super.toString().substring(0);
  }

  void foo() { // (1) => foo should be alphabetically before toString.
    throw UnimplementedError();
  }
}

class Ordering {
  void foo() {
    throw UnimplementedError();
  }

  const Ordering(); // (2) => constructors should be before overridden-methods.

  @override
  String toString() {
    return super.toString().substring(0);
  }
}
```

**What did you expect to happen?**

1. Another lint: `public-methods should be before overridden-methods.`
2. Lint should apear above `foo` function: `public-methods should be before constructors`

**What actually happened?**

Look at comments in code.
