### ISSUE TITLE
[BUG] Overriding extended config leads to rules configuration loss

### ISSUE THREAD

**Issue by plastb1r** [dart-code-checker/dart-code-metrics#398]
When disabling unique rules in analysis_options.yaml like that:

```
dart_code_metrics:
  rules:
    avoid-returning-widgets: false
```

this disables the inherited order of class elements.

To solve this problem, you have to duplicate rules from the library, which is not great:

```
dart_code_metrics:
  rules:
    avoid-returning-widgets: false
    member-ordering-extended: 
      alphabetize: false
      order:
        - public-static-const-fields
        - private-static-const-fields
        - public-static-final-fields
        - private-static-final-fields
        - public-static-fields
        - private-static-fields
        - public-final-fields
        - private-final-fields
        - public-fields
        - public-getters-setters
        - private-fields
        - private-getters-setters
        - constructors
        - named-constructors
        - factory-constructors
        - overridden-methods
        - public-static-methods
        - public-methods
        - protected-methods
        - private-static-methods
        - private-methods
```
