### ISSUE TITLE
[Question] What do you think of the ability for developers to add Custom Rules?

### ISSUE THREAD

**Issue by hisaichi5518** [dart-code-checker/dart-code-metrics#424]
If I want to set my own lint rule for my library or my app, I need to create my own analyzer_plugin. I am using dart-code-metrics and I want to achieve that only with dart-code-metrics.

So I would like to ask what you think about adding a setting to dart-code-metrics for developers to set their own rules for their libraries and apps.

For example, you may want to set up a custom rule as shown below.
This has been inspired by the build_runner configuration.

```yaml
analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  import: 'rules/custom_rules.dart'
  rule_factories: ['myCustomRuleBuilder']
  ...
```
```dart
// rules/custom_rules.dart
import '...';

Rule myCustomRuleBuilder(_) => MyCustomeRule();
```
