### ISSUE TITLE
[BUG]  Double suggestions

### ISSUE THREAD

**Issue by theSharpestTool** [dart-code-checker/dart-code-metrics#451]
* **Dart code metrics version:** 4.2.1
* **Dart sdk version:** 2.14.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
analyzer:
  exclude:
    - test/**
  plugins:
    - dart_code_metrics
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting: 5
    number-of-parameters: 5
    number-of-methods: 10
  metrics-exclude:
    - test/**
  rules:
    - avoid-ignoring-return-values
    - avoid-non-null-assertion
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-match-file-name
    - prefer-trailing-comma
```

</details>

**What did you do? Please include the source code example causing the issue.**

Trigger suggestions list on VS Code Mac OS

**What did you expect to happen?**

Suggestions list will be displayed

**What actually happened?**

Each suggestion on each widget displayed twice.
 
<img width="558" alt="Screenshot 2021-09-10 at 17 18 26" src="https://user-images.githubusercontent.com/41484688/132868096-787ba599-37c2-4132-b4fc-4a17e8202f73.png">

If I remove 
```yaml   
  plugins:
    - dart_code_metrics
 ```
 from `analysis_options.yaml` and restart analysis server, the suggestions displayed correctly
