### ISSUE TITLE
[BUG] excludes not working on Windows 10

### ISSUE THREAD

**Issue by c-antin** [dart-code-checker/dart-code-metrics#509]
* **Dart code metrics version:** 4.4.0
* **Dart sdk version:** 2.13.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 4
    source-lines-of-code: 50
    weight-of-class: 0.33
  metrics-exclude:
    - test/**
    - lib/json/**
  rules:
    avoid-unused-parameters:
      exclude:
        - lib/json/builders/**
    binary-expression-operand-order: true
    double-literal-format: true
    member-ordering-extended:
      exclude:
        - lib/json/builders/**
      order:
        - static-const-fields
        - static-fields
        - static-methods
        - constructors
        - named-constructors
        - factory-constructors
        - const-fields
        - late-fields
        - final-fields
        - fields
        - getters-setters
        - methods
    no-boolean-literal-compare: true
    no-empty-block: true
    no-equal-arguments: true
    no-equal-then-else: true
    no-magic-number: true
    no-object-declaration: true
    prefer-conditional-expressions: true
    prefer-trailing-comma: true
    always-remove-listener: true
    avoid-returning-widgets: true
    avoid-unnecessary-setstate: true
    avoid-wrapping-in-padding: true
    prefer-extracting-callbacks:
      ignored-named-arguments:
        - onPopPage
```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart
static-const-fields should be before constructors.
dartmember-ordering-extended
```

**What did you expect to happen?** Excludes working on Windows 10

**What actually happened?** Excludes not working

**Are you willing to submit a pull request to fix this bug?** no
