### ISSUE TITLE
[Question] How to specify multiple folders in GitHub Action?

### ISSUE THREAD

**Issue by dvorapa** [dart-code-checker/dart-code-metrics#617]
**What do you want to discuss?**
This was my attempt (doesn't work, but should be yaml correct):
```
name: Dart Code Metrics

on: [push]

jobs:
  check:
    name: dart-code-metrics-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: [example, lib]
```
