### ISSUE TITLE
[Question] Rule to ignore freezed files

### ISSUE THREAD

**Issue by leech001** [dart-code-checker/dart-code-metrics#620]
Can you tell me how to set a rule in` rules-exclude` to ignore all `*.freezed.dart` files?

**Comment by dkrutskikh** [comment]
Hi @leech001. We support global excludes, and I recommend use them. 

For example:

```yaml
analyzer:
  exclude:
    - "build/**"
    - "script/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```
