### ISSUE TITLE
[Command change] check-unused-l10n hide private members

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#647]
* **Dart code metrics version:** 4.9.1
* **Dart sdk version:**  2.15.0 (stable)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/generated/**.dart"
    - "**/*.gform.dart"
    - "ios/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: error
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 27
    source-lines-of-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - e2e/**
    - ios/**
  rules:
    - always-remove-listener
    - avoid-non-null-assertion
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-unused-parameters
    - avoid-wrapping-in-padding
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-single-widget-per-file
    - prefer-trailing-comma
    - no-equal-then-else
    - binary-expression-operand-order
```

</details>

**What did you do? Please include the source code example causing the issue.**

```sh
flutter pub run dart_code_metrics:metrics check-unused-l10n lib -p ^S$
```

**Code details**
```dart
class S {
  S();

  static S? _current;

  static S get current {
    assert(_current != null,
        'No instance of S was loaded. Try to initialize the S delegate before accessing S.current.');
    return _current!;
  }
…
}

```

**What did you expect to happen?**
the command ignore private members as `_current`

**What actually happened?**
the command consider `_current` as unused l10n
```
⚠ unused _current
at lib/generated/l10n.dart:18:3
```
