### ISSUE TITLE
[BUG] Metrics don't work correctly with imported `analysis_options.yaml` when run as global executable

### ISSUE THREAD

**Issue by solid-yuriiprykhodko** [dart-code-checker/dart-code-metrics#665]
* **Dart code metrics version:** 4.9.1
* **Dart sdk version:** Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"

<details>
<summary>Configuration</summary>

The full configuration as well as full instructions to reproduce the issue are hosted here: https://github.com/solid-yuriiprykhodko/metrics_cc_repro/tree/global-exe

```yaml
include: 'package:solid_lints/analysis_options.yaml'
```

Contents of `solid_lints/analysis_options.yaml`:

```yaml
analyzer:
  exclude:
    # General generated files
    - '**/*.g.dart'
    - '**/*.gr.dart'

    # Flutter
    - 'lib/generated_plugin_registrant.dart'

    # mockito
    - '**/*.mocks.dart'

    # freezed
    - '**/*.freezed.dart'

    # protobuf
    - '**/*.pb.dart'

    # test_coverage
    - test/.test_coverage.dart

  # Dart Code Metrics plugin (https://dartcodemetrics.dev/) provides many additional rules
  # that helped to automate some pieces of our internal team code style based on the best
  # industry practices.
  plugins:
    - dart_code_metrics
  strong-mode:
    # We've seen errors tied to use of implicit operations similar to the ones described in
    # https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks.
    # When we do things explicitly there is less room for errors.
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error

dart_code_metrics:
  metrics:
    # NIST 500-235 item 2.5
    cyclomatic-complexity: 10

    # McConnell, S. (2004), Chapter 7.5: High-Quality Routines: How To Use Routine Parameters. Code Complete, Second Edition, Redmond, WA, USA: Microsoft Press. 174-180
    number-of-parameters: 7

    # McConnell, S. (2004), Chapter 7.4: High-Quality Routines: How Long Can a Routine Be?. Code Complete, Second Edition, Redmond, WA, USA: Microsoft Press. 173-174
    source-lines-of-code: 200

    # We use source-lines-of-code instead of this as we don't want to count comment or blank lines.
    # lines-of-code: 50
  rules:
    - avoid-global-state
    - avoid-late-keyword
    - avoid-non-null-assertion
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - double-literal-format
    - member-ordering-extended:
        order:
          - fields
          - getters-setters
          - constructors
          - methods
    - newline-before-return
    - no-empty-block
    - no-equal-then-else
    - no-magic-number
    - prefer-conditional-expressions
    - prefer-first
    - prefer-last
    # This improves navigation by matching file content and file name.
    - prefer-match-file-name
  anti-patterns:
    - long-method
    - long-parameter-list

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    # available in later releases
    #    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    # available in later releases
    #    - conditional_uri_does_not_exist
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - deprecated_consistency
    # - diagnostic_describe_all_properties
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    # available in later releases
    #    - no_leading_underscores_for_library_prefixes
    #    - no_leading_underscores_for_local_identifiers
    - no_logic_in_create_state
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    # Not used, as the default app template has a single statement return code generated.
    # While this could be beneficial for Dart projects and maintaining code style, we are unaware
    # of any substantial evidence that improves code when using expression function body
    # vs single statement return. We are considering including this in Dart only lints.
    #   - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - public_member_api_docs
    - recursive_getters
    - require_trailing_commas
    # available in later releases
    #    - secure_pubspec_urls
    - sized_box_for_whitespace
    # available in later releases
    #    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    # We tend to use class organization close to standard Java convention, where fields come first.
    # Martin, R. C. & Coplien, J. O. (2013), Chapter 10: Classes. Clean code: a handbook of agile software craftsmanship , Prentice Hall , Upper Saddle River, NJ [etc.] . 136
    #    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    # available in later releases
    #    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_test_throws_matchers
    - valid_regexps
    - void_checks
```
</details>

**What did you do? Please include the source code example causing the issue.**

I've tried to use a predefined set of code metric thresholds, running the analysis from a global `metrics` executable.

The configuration as well as full instructions to reproduce the issue are hosted here: https://github.com/solid-yuriiprykhodko/metrics_cc_repro/tree/global-exe

**What did you expect to happen?**

`metrics` executable to output to contain warnings about high cyclomatic complexity of a file.

**What actually happened?**
Running metrics locally (`dart run dart_code_metrics:metrics analyze test`) works fine, but the global executable output does not find any issues.

**Are you willing to submit a pull request to fix this bug?**
Not anytime soon.
