### ISSUE TITLE
[BUG] 7~15GB memory usage for this single plugin - possibly serious memory leak? (Flutter 2.10.2)

### ISSUE THREAD

**Issue by fzyzcjy** [dart-code-checker/dart-code-metrics#718]
Hi thanks for the lib! However, to analyze our codebase (quite small, just 150k lines of code), this analyzer plugin eats about 10GB of memory! You know, even for Intellij IDEA which is known to be memory-eater and is configured with a large heap, it only has about 4GB memory.  But this package itself is twice as big as the IDE...

The following screenshot shows a 7GB case, where I restart the analyze server and do nothing. After doing some operations, the memory seems to increase. Sometimes I do see about 10GB.

![image](https://user-images.githubusercontent.com/5236035/156089350-58fdaa6d-c001-414f-a0d8-73e1656d2e0b.png)

---

* **Dart code metrics version:** latest stable
* **Dart sdk version:** 2.10

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    source-lines-of-code: 80
  metrics-exclude:
    - test/**
  rules:
    - avoid-global-state
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - no-boolean-literal-compare
    - prefer-last
    - avoid-unnecessary-setstate
    - avoid-non-null-assertion
  anti-patterns:
    - long-method
```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart

```

**What did you expect to happen?**

**What actually happened?**

**Are you willing to submit a pull request to fix this bug?**
