### ISSUE TITLE
[BUG] metrics stopped working at version 4.12.0

### ISSUE THREAD

**Issue by GabrielCR99** [dart-code-checker/dart-code-metrics#737]
* **Dart code metrics version:** 4.12.0
* **Dart sdk version:** 2.16.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
include: package:flutter_lints/flutter.yaml

analyzer:

  plugins:
    - dart_code_metrics

  exclude:
    - lib/generated/**
    - lib/app/modules/**/*.g.dart
    - lib/app/modules/**/**/*.g.dart
    - lib/generated_plugin_registrant.dart
    - "**/*.freezed.dart"

  errors:
    prefer_relative_imports: warning
    constant_identifier_names: warning
    non_constant_identifier_names: warning
    unused_import: warning
    avoid_redundant_argument_values: warning
    require_trailing_commas: warning
    always_put_required_named_parameters_first: warning
    prefer_single_quotes: warning


linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    cascade_invocations: true
    prefer_const_constructors: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    require_trailing_commas: true
    always_put_required_named_parameters_first: true
    overridden_fields: false
    unawaited_futures: false
    eol_at_end_of_file: true
    join_return_with_assignment: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
    
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 6
    source-lines-of-code: 50
    halstead-volume: 150
    lines-of-code: 100
    number-of-methods: 10
    weight-of-class: 0.33

  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - double-literal-format
    - prefer-first
    - prefer-conditional-expressions
    - prefer-const-border-radius
```

</details>

**What did you expect to happen?** Linter should show warn/info about code, but doesn't show anything even after restarting IDE/PC several times.

**What actually happened?** The package stopped working at version 4.12.0, but what I actually think is that randomly, it's pointing to pub-cache directory, and not the right directory which is the project one. I don't know how to fix this, I've tried to delete the project and clone it again but it didn't work, unfortunately.
