### ISSUE TITLE
[BUG] `Could not find a file named "pubspec.yaml"` error

### ISSUE THREAD

**Issue by DetachHead** [dart-code-checker/dart-code-metrics#748]
* **Dart code metrics version:** 4.13.0
* **Dart sdk version:** 2.16.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true  
    avoid_unused_constructor_parameters: true

dart_code_metrics:
  rules:
    - avoid-unused-parameters
    - no-empty-block
```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart
void foo(String value) {}
```

**What did you expect to happen?**
no crash
**What actually happened?**
```
>dart run dart_code_metrics:metrics analyze lib 
Could not find a file named "pubspec.yaml" in "C:\Users\amogus\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-36.0.0".
#0      new Pubspec.load (package:pub/src/pubspec.dart:288:7)
#1      new Package.load (package:pub/src/package.dart:149:27)
#2      SystemCache.load (package:pub/src/system_cache.dart:113:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:112:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:107:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:232:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:296:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:67:29)
#13     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
**Are you willing to submit a pull request to fix this bug?**

probs not, i'm very new to flutter/dart
