### ISSUE TITLE
[BUG] No error code returned for technical-debt metric

### ISSUE THREAD

**Issue by NickBalnaves** [dart-code-checker/dart-code-metrics#770]
* **Dart code metrics version:** 4.13.0
* **Dart sdk version:** 2.16.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
dart_code_metrics:
  metrics:
    technical-debt:
      threshold: 0
      todo-cost: 0
      deprecated-annotations-cost: 0
      ignore-cost: 1
      ignore-for-file-cost: 0
      as-dynamic-cost: 0
      file-nullsafety-migration-cost: 0
```

</details>

**What did you do? Please include the source code example causing the issue.**

```
dart run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings
```

**What did you expect to happen?**
The above command to produce an error code specifying using an ignore comment. 

**What actually happened?**
There was an alarm raised for technical debt but no error code was returned. Even when setting `--set-exit-on-violation-level` there is no error code returned.

**Are you willing to submit a pull request to fix this bug?**
No
