### ISSUE TITLE
[Rule change] make prefer-moving-to-variable configurable

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#798]
It would be nice to have the possibility to exclude folders from analyzing (like in `prefer-match-file-name`):
```yaml
    - prefer-moving-to-variable:
        exclude:
          - test/**
```
