### ISSUE TITLE
[BUG] no errors reported when running on current directory (`.`)

### ISSUE THREAD

**Issue by DetachHead** [dart-code-checker/dart-code-metrics#799]
* **Dart code metrics version:** 4.13.0
* **Dart sdk version:** 2.16.2

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
analyzer:
  plugins:
    - dart_code_metrics
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/generated_plugin_registrant.dart
```

</details>

**What did you do? Please include the source code example causing the issue.**

```
>flutter pub run dart_code_metrics:metrics analyze .
✔ no issues found!

>flutter pub run dart_code_metrics:metrics analyze lib
lib\screens\report.dart:
STYLE   Block is empty. Empty blocks are often indicators of missing code.
        lib\screens\report.dart:85:29
        no-empty-block : https://dartcodemetrics.dev/docs/rules/common/no-empty-block

STYLE   Block is empty. Empty blocks are often indicators of missing code.
        lib\screens\report.dart:90:27
        no-empty-block : https://dartcodemetrics.dev/docs/rules/common/no-empty-block

STYLE   Block is empty. Empty blocks are often indicators of missing code.
        lib\screens\report.dart:104:29
        no-empty-block : https://dartcodemetrics.dev/docs/rules/common/no-empty-block
```

**What did you expect to happen?**
same errors when running in `.`

**What actually happened?**
no errors found
