### ISSUE TITLE
[BUG] How to reuse and override the configuration when it is imported

### ISSUE THREAD

**Issue by ValentinVignal** [dart-code-checker/dart-code-metrics#814]
I have a root `analysis_option.yaml` in my project with (for example) those rules:

```yaml
# analysis_option.yaml
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  rules:
    - prefer-trailing-comma
    - no-empty-block
```

In our `test/` folder we have another `analysis_option.yaml` file that includes the root one and overrides some rules, to override/disable some of them. As an example:

```yaml
# test/analysis_option.yaml
include: ../analysis_options.yaml

analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: ignore
```

--- 

Now, in my tests, let's say I want to keep the rule `prefer-trailing-comma` but I want to disable `no-empty-block`. 

I made several attempts, but I can't manage to get the result I want:

<details>
<summary>Attempt 1</summary>

```yaml
# analysis_option.yaml
dart_code_metrics:
  rules:
    - prefer-trailing-comma
    - no-empty-block:
        exclude:
          - text/**
```

```yaml
# test/analysis_option.yaml
include: ../analysis_options.yaml
```

Both, `prefer-trailing-comma` and `no-empty-block` are linted in the test files.
</details>

<details>
<summary>Attempt 2</summary>

```yaml
# analysis_option.yaml
dart_code_metrics:
  rules:
    - prefer-trailing-comma
    - no-empty-block
```

```yaml
# test/analysis_option.yaml
include: ../analysis_options.yaml

dart_code_metrics:
  rules:
    - no-empty-block: false
```

Both, `prefer-trailing-comma` and `no-empty-block` are linted in the test files.
</details>

<details>
<summary>Attempt 3</summary>

```yaml
# analysis_option.yaml
dart_code_metrics:
  rules:
    - prefer-trailing-comma
    - no-empty-block
```

```yaml
# test/analysis_option.yaml
include: ../analysis_options.yaml

dart_code_metrics:
  rules:
    - no-empty-block:
        exclude: "**/*"
```

Both, `prefer-trailing-comma` and `no-empty-block` are linted in the test files.
</details>

**Comment by incendial** [comment]
Interesting, second approach should work. But I've never saw anyone using the same approach with a separate analysis_options for the tests folder.

Again asking for an example to speed up the investigation 🙂

**Comment by ValentinVignal** [comment]
@incendial I created a repo/branch here https://github.com/ValentinVignal/flutter_app_stable/tree/dart-code-metrics/nested-analysis-option

**Comment by incendial** [comment]
Thanks!

**Comment by incendial** [comment]
Sorry for the delay, investigating

**Comment by incendial** [comment]
So, thank you again for the example, I'll cover all listed attempts, just to clarify

1. Doesn't work, coz when you import configuration into another configuration, it just gets copied without any path adjustments
2. Found a bug in this one, fix is on the way 🚀 . In short, we didn't properly parse `:true` `:false` configurations and didn't merge them with just string listings like you have in your main config
3. Tested this, should work fine with '**' ignore
<img width="443" alt="Screenshot 2022-04-30 at 13 49 37" src="https://user-images.githubusercontent.com/21116742/166100647-888e622a-5943-44cd-83fb-abf17dbb6f6e.png">

**Comment by incendial** [comment]
Available in 4.15.0 🚀

**Comment by romatallinn** [comment]
@incendial so it should work, right? For me, if I add a new `analysis_options.yaml` to sub-directory, it disappears from the report. 

For example,

```yaml
// analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/generated/**"
    - "test/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options.dart"

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
  anti-patterns:
    - long-method
    - long-parameter-list
  rules:
    - newline-before-return: false
```


```yaml
// lib/models/analysis_options.yaml
include: ../../analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
```

So, I am trying to generate an HTML report. With this second `analysis_options.yaml`, everything is generated. But if add it, `models` disappears from the report. Any ideas why?
