### ISSUE TITLE
[New rule] avoid-restricted-imports

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#820]
**Please describe what the rule should do:**

I propose a rule similar to ESLint [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports). There might be many use cases for it. In our project (a design system component library) we need to restrict import from Flutter `material.dart` because we do not use Material Design and must not depend on it anywhere.

Without configuration this rule should simply do nothing. I think we need to have a flexible configuration here, the most important for me is to configure rule per file glob pattern.

In nearest future I would like to discuss this rule and also I plan to provide a PR.

**If your rule is inspired by other please provide link to it:**

[no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports).

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[x] Suggests an alternate way of doing something (suggestion)
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about (it will be better if you can provide both good and bad examples):**

Just possible rule configuration:

```yaml
- avoid_restricted_imports
   - paths: ["some/**/folder/*.dart", "another/folder/**.dart"]
     deny: ["package:flutter/material.dart"]
     message: "Do not import Flutter Material Design library, we should not depend on it!"
   - paths: ["core/*.dart"]
     deny: ["package:flutter_bloc/flutter_bloc.dart"]
     message: "State management should be not used inside "core" folder."
```

**BAD**

```dart
import "package:flutter/material.dart";
import "package:flutter_bloc/flutter_bloc.dart";
```

**GOOD**
```
No restricted imports in listed folders.
```

**Are you willing to submit a pull request to implement this rule?**
Yes, in a few weeks.
