### ISSUE TITLE
[Question] Different output for same code in pipeline?

### ISSUE THREAD

**Issue by codeOfJannik** [dart-code-checker/dart-code-metrics#842]
If I locally run `flutter pub global run dart_code_metrics:metrics analyze --fatal-style --fatal-performance --fatal-warnings lib` with rules in the analysis_options.yaml in place, I don't receive warnings anymore since I have resolved all of them. But when the same command is executed inside a step of the bitbucket-pipeline.yaml I receive 46 warnings, most of them _avoid-dynamic_.

When I check the linked line of code there's no dynamic type used. That are just lines like: `class Museum with EquatableMixin {`

Why is there this difference in the pipeline? Is there anything I can adjust to get the command running properly in the pipeline?

**Comment by incendial** [comment]
@codeOfJannik could you share your `analysis_options.yaml` and  `bitbucket-pipeline.yaml` Dart Code Metrics configs?

**Comment by codeOfJannik** [comment]
**analysis-options.yaml**
```yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/**
    - plugins/**
  errors:
    missing_required_param: warning
    parameter_assignments: warning
    missing_return: error
    todo: ignore

dart_code_metrics:
  metrics:
    - cyclomatic-complexity: 20
    - halstead-volume: 150
    - lines-of-code: 100
    - maintainability-index: 50
    - maximum-nesting-level: 5
    - number-of-methods: 10
    - number-of-parameters: 6
    - source-lines-of-code: 50
    - technical-debt:
        threshold: 1
        todo-cost: 161
        ignore-cost: 320
        ignore-for-file-cost: 396
        as-dynamic-cost: 322
        deprecated-annotations-cost: 37
        file-nullsafety-migration-cost: 41
        unit-type: "USD"
    - weight-of-class: 0.33
  rules:
    # Common
    - avoid-collection-methods-with-unrelated-types
    - avoid-dynamic:
        exclude:
          - test/**
    - avoid-global-state
    - avoid-late-keyword:
        exclude:
          - test/**
          - lib/main.dart
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptance-level: 2
    - avoid-non-null-assertion
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - member-ordering:
      alphabetize: true
      order:
        - public-fields
        - private-fields
        - constructors
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments:
        ignored-parameters:
          - height
          - width
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        exceptions:
          - id
          - ok
    - prefer-correct-type-name:
        max-length: 44
    - prefer-first
    - prefer-last
    - prefer-immediate-return
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-moving-to-variable:
        exclude:
          - test/**
    - prefer-trailing-comma
    # Flutter specific
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true

  anti-patterns:
    - long-method
    - long-parameter-list

  metrics-exclude:
    - test/**

```

**bitbucket-pipelines.yaml**
```yaml
image: cirrusci/flutter:latest

pipelines:
  pull-requests:
    "**":
      - step:
          name: "Dependencies"
          caches:
            - flutter-pub-cache
          script:
            - git submodule update --recursive --init
            - flutter pub get
            - flutter packages pub global activate intl_utils
            - flutter pub global run intl_utils:generate
          artifacts:
            - lib/generated/**
            - plugins/**
            - .dart_tool/**
      - step:
          name: "Static code analysis"
          script:
            - flutter pub global activate dart_code_metrics
            - flutter pub global run dart_code_metrics:metrics analyze --fatal-style --fatal-performance --fatal-warnings lib
            # - flutter pub run dart_code_metrics:metrics check-unused-code lib
            # - flutter pub run dart_code_metrics:metrics check-unused-files lib
            # - flutter pub run dart_code_metrics:metrics check-unused-l10n lib
      - parallel:
          - step:
              name: "Build Android"
              caches:
                - gradle
                - gradlewrapper
                - android-sdk
                - flutter-pub-cache
              script:
                - flutter build apk --flavor dev -t lib/main_dev.dart
          - step:
              name: "Unit Tests"
              caches:
                - flutter-pub-cache
              script:
                - flutter test test/unit_tests
          - step:
              name: "Widget Tests"
              caches:
                - flutter-pub-cache
              script:
                - flutter test test/widget_tests/
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
    android-sdk: /opt/android-sdk-linux
    flutter-pub-cache: ~/.pub-cache

```
