### ISSUE TITLE
[BUG] The specified file can not be found. Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat upgrade

### ISSUE THREAD

**Issue by FMorschel** [dart-code-checker/dart-code-metrics#851]
* **Dart code metrics version:** 4.15.0
* **Dart sdk version:** 2.17.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    missing_required_param: error

dart_code_metrics:
  rules:
    - double-literal-format
    - format-comment
    - member-ordering-extended:
        alphabetize: true
        order:
          - constructors
          - public-fields
          - private-fields
          - getters-setters
          - public-methods
          - private-methods
    - no-equal-arguments: 
        ignored-parameters:
          - height
          - width
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-immediate-return
    - prefer-last

    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets:
        ignored-names:
          - testFunction
        ignored-annotations:
          - allowedAnnotation
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onPressed

```

</details>

I just followed the instructions to run the package with VSCode Analyzer and it didn't work. I tried to restart the Analysis Server, run `flutter clean` and `pub get` again, but nothing really did anything.

**What did you expect to happen?**
See the lint warnings and infos.

**What actually happened?**
Nothing.
Then I opened Analyzer Diagnostics, over plugin, I found:
![image](https://user-images.githubusercontent.com/52160996/168656532-53502043-b126-4b5f-b406-424572180555.png)

I looked at dart-sdk/bin folder and this is what I have:
![image](https://user-images.githubusercontent.com/52160996/168656835-162b07da-dd9c-4639-b4fa-fa3abcf6bd2f.png)

<details>
<summary>Exception</summary>

```
ProcessException: The specified file can not be found.

  Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat upgrade
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      PluginManager._computeFiles (package:analysis_server/src/plugin/plugin_manager.dart:641:28)
#4      PluginManager.filesFor (package:analysis_server/src/plugin/plugin_manager.dart:462:14)
#5      PluginManager.addPluginToContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:328:23)
#6      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:68:19)
#7      AnalysisDriver.configure (package:analyzer/src/dart/analysis/driver.dart:555:33)
#8      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:137:12)
#9      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:67:36)
#10     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:449:40)
#11     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:444:41)
#12     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:562:17)

```

</details>

**Are you willing to submit a pull request to fix this bug?**
I'm not qualified for this.
