### ISSUE TITLE
[BUG] Cannot override rules

### ISSUE THREAD

**Issue by fzyzcjy** [dart-code-checker/dart-code-metrics#860]
* **Dart code metrics version:**latest
* **Dart sdk version:**latest

Hi thanks for the library! For example, I have a analysis yaml like:

```
dart_code_metrics:
  rules:
    - avoid-non-ascii-symbols
```

but I want to disable this rule for a few packages:

```
include: package:common_dart_core/my_analysis_options.yaml

dart_code_metrics:
  rules:
    - avoid-non-ascii-symbols:
        severity: none
```

But this seems impossible as the package does not recognize it.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml

```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart

```

**What did you expect to happen?**

**What actually happened?**

**Are you willing to submit a pull request to fix this bug?**
