### ISSUE TITLE
[New rule or command] unused dependencies

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#905]
**Please describe what the rule should do:** check and suggest removing unused packages in pubspec.yaml (dependencies section)

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[ x ] Suggests an alternate way of doing something (suggestion)
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about (it will be better if you can provide both good and bad examples):**

```yaml
dependencies:
  firebase_analytics: ^9.0.2 <<<<< report as unused
  firebase_core: ^1.2.0
  firebase_messaging: ^11.4.0
  flutter:
    sdk: flutter
  rxdart: ^0.27.3

dev_dependencies:
  dart_code_metrics: ^4.13.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
```
