### ISSUE TITLE
[Feature] Support `// ignore:` for metrics

### ISSUE THREAD

**Issue by vasilich6107** [dart-code-checker/dart-code-metrics#935]
* **Dart code metrics version:** 4.16.0
* **Dart sdk version:** >=2.17.0 <3.0.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
include: package:lint/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "lib/generated/**"
    - "lib/generated_*"
    - "lib/i18n/messages_*.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.graphql.dart"
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 6
    maximum-nesting-level: 5
    source-lines-of-code: 40
  metrics-exclude:
    - test/**
  rules:
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-trailing-comma
    - prefer-conditional-expressions
    #      flutter
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
  rules-exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    depend_on_referenced_packages: false
```

</details>

**What did you do? Please include the source code example causing the issue.**

```dart
extension GoRouterStateExt on GoRouterState {
  // ignore: number-of-parameters
  GoRouterState copyWith(
    GoRouteInformationParser delegate, {
    String? location,
    String? subloc,
    String? name,
    String? path,
    String? fullpath,
    Map<String, String>? params,
    Map<String, String>? queryParams,
    Object? extra,
    Exception? error,
    ValueKey<String>? pageKey,
  }) =>
      GoRouterState(
        delegate,
        location: location ?? this.location,
        subloc: subloc ?? this.subloc,
        name: name ?? this.name,
        path: path ?? this.path,
        fullpath: fullpath ?? this.fullpath,
        params: params ?? this.params,
        queryParams: queryParams ?? this.queryParams,
        extra: extra ?? this.extra,
        error: error ?? this.error,
        pageKey: pageKey ?? this.pageKey,
      );
}
```

**What did you expect to happen?**
Dart code metrics should ignore the issue

**What actually happened?**
Dart code metrics does not ignore the issue
<img width="504" alt="image" src="https://user-images.githubusercontent.com/6721286/180485045-3ac574c0-6125-4247-87f9-316a0a6fc7f2.png">

**Are you willing to submit a pull request to fix this bug?**
not for now
